title: dataDicGen
logo: /assets/img/Marcelo.png
description: Data Dictionary generator for Salesforce by Marsson
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
github:
  github.repository_url: https://github.com/marsson/dataDicGen
